class AttendanceStatus:
    EARLY_CHECKED_OUT = "EARLY_CHECKED_OUT"
    IDLE = "IDLE"
    WORKING = "WORKING"
    OVERTIME_WORKING = "OVERTIME_WORKING"
    CHECKED_OUT = "CHECKED_OUT"
    ON_LEAVE = "ON_LEAVE"
    WORK_TIME_OVER = "WORK_TIME_OVER"
    NOT_CHECKED_IN = "NOT_CHECKED_IN"
    CHECKED_OUT_OT = "CHECKED_OUT_OT"

    # 알림용 (백엔드 Enum에도 반드시 추가!)
    NEED_BREAK_NOTIFICATION = "NEED_BREAK_NOTIFICATION"
    NEED_OVERTIME_NOTIFICATION = "NEED_OVERTIME_NOTIFICATION"
    NOT_CHECKED_IN_NOTIFICATION = "NOT_CHECKED_IN_NOTIFICATION"

class AttendanceType:
    # 실제 근무 타입(반차, 보상반일 등)
    WORKDAY = "근무일"
    OUTWORK = "외근"
    HALF_DAY = "반차"
    QUARTER_DAY = "반반차"
    LEAVE = "연차"
    COMP_HALF = "보상반일"
    COMP_FULL = "보상종일"
    VACATION = "휴가"

class AttendanceTime:
    WORK_HOURS = 9
    BREAK_HOURS = 10
    OVERTIME_HOURS = 10.5
    HALF_DAY_HOURS = 4
    QUARTER_DAY_HOURS = 2
    AFTER_WORK_CHECK_MINUTES = 20
    BEFORE_BREAK_CHECK_MINUTES = 5
    BEFORE_OVERTIME_CHECK_MINUTES = 5
    HALF_DAY_CHECK_MINUTES = 50
    QUARTER_DAY_CHECK_MINUTES = 20